language: go
dist: trusty
go:
- 1.6
before_script:
- npm install -g chrome-har-capturer
addons:
  chrome: stable
before_install:
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 &
script:
- run.sh
