language: go

dist: trusty

go:
- 1.6

addons:
  chrome: stable

before_install:
- nvm install 7.10.0
- nvm use 7.10.0
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 &
- npm install -g chrome-har-capturer


install: sh run.sh
